nelmio_cors:
    defaults:
        allow_origin: ['*'] # Ou spécifiez l'origine, ex: ['http://localhost:3000']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/': # Appliquer la configuration aux routes commençant par /api/
            allow_origin: ['http://127.0.0.1:4200', 'http://localhost:4200']